services:

  alpinelinux-jboss:
    build: ./setup-images/alpinelinux-jboss/

    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"

    depends_on:
      - mssqlserver

  mssqlserver:
    build: ./setup-images/mssqlserver-2019/

    ports:
      - "1433:1433"

    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssW0rd





