services:

  alpinelinux-jboss:
    build: ./setup-images/alpinelinux-jboss/

    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"

    depends_on:
      - mssqlserver

  mssqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest

    ports:
      - "1433:1433"

    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssW0rd

    volumes:
      - ./sources/instnwnd.sql:/tmp/instnwnd.sql

    command: ["/bin/sh", "-c", "/opt/mssql-tools18/bin/sqlcmd -No -H sql1 -U sa -P P@ssW0rd -i /tmp/instnwnd.sql"]




