services:

  alpinelinux-jboss:
    image: alpinelinux-jboss:latest

    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"

    depends_on:
      - mssqlserver

  mssqlserver:
    image: mssqlserver-2019:latest

    ports:
      - "1433:1433"

    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssW0rd

    #command: ["/bin/sh", "-c", "sleep 15 && /opt/mssql-tools18/bin/sqlcmd -No -H mssql -U sa -P P@ssW0rd -i /tmp/instnwnd.sql"]





